config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'pages#index'
  resources :music_products, only: [:index,:show]
  get :search, to: 'music_products#search'


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music_product.rb
class MusicProduct < ApplicationRecord
	has_one_attached :image
	has_many_attached :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/music_products_controller.rb
class MusicProductsController < ApplicationController

	def index
		@music_products = MusicProduct.all
	end

	def show
		@music_product = MusicProduct.find(params[:id])
	end


	def search
		@search = params[:search]
		@music_products = MusicProduct.where("name LIKE '%#{params[:search]}%'")
	end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@music_products = MusicProduct.limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/music_products_helper.rb
module MusicProductsHelper

	def music_product_image(image, width:200, height:200)
		image_tag (image.attached? ? image : '/undefined.png'), width: width, height: height, class: 'image'
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav>

	<div style="display: inline-block; margin-left: 20px;"><%= link_to root_path do %>
		OLCorporation		
	<%end%>
</div>
<div style="display: inline-block; margin-left: 20px;">
	<%= link_to music_products_path do %>
		Каталог		
	<%end%>
</div>
<div style="display: inline-block; margin-left: 20px;">
	  <%= form_tag(search_path, :method => "get", id: "search-form", name: "f1", enforce_utf8: false) do %>
    <div class="input-group" >
      <%= text_field_tag :search, params[:search], placeholder: "Search products", class: "form-control", name: "search" %>
      <div class="input-group-btn">
        <button class="btn btn-secondary" style="height: 30px; text-align: center;">
        	<p style="vertical-align: text-bottom;">Search</p>
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </div>
    </div>
  <% end %> 
</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>First</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <p class="h5 my-0 me-md-auto fw-bold">olEnginer</p>
    <p style=" margin-left: 50px; ">
      <%= render "layouts/navbar"%>
    </p>
  </header>

  <div class="container">
      <%= yield %>
  </div>

  <footer style="background: #333; margin-top: 30px;" class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a>.</p>
  </div>
</footer>

  </body>
</html>

app/views/music_products/_music_product.html.erb
<%= link_to  music_product_path(music_product) do %>
	<div class="col-2"><%= music_product_image(music_product.image) %>
		<%= music_product.name %>
	</div>
<%end%>

app/views/music_products/index.html.erb
<h1>Каталог</h1>
<div class="row">
	<%= render @music_products%>
</div>

app/views/music_products/search.html.erb
<h1>Результат пошуку за "<%= @search%>"</h1>
<h5>Кількість результатів <%= @music_products.count%></h5>
<div> <%= "Нічого не знайдено" if @music_products.count==0%></div>
<div class="row"><%= render @music_products%></div>

app/views/music_products/show.html.erb
<h1 align="center">
	<%= @music_product.name %>
</h1>
<div style="display: flex; flex-direction: row;">
	<div><%= music_product_image @music_product.image%></div>
	<div style="margin-left: 10px;">
		Prefomer:<br>
		Autor:<br>
		Album:<br>
		Price:<br>
	</div>
	<div style="height: 200px;">
		<div style=" margin-left: 20px;">
			<%= @music_product.perfomet%><br>
			<%= @music_product.autor%><br>
			<%= @music_product.album%><br>
			<%= @music_product.prise%><br>
		</div>
	</div>
</div>
<div class="">
	<% @music_product.images.each do |image|%>
		<%= image_tag image, width: 300, height: 200%>
	<%end%>
</div>

app/views/pages/index.html.erb
<h1>OLCorporation</h1>
<p>Тут ви знайдете музику, яку ви шукали!</p>
<% render @music_products%>